name: Build and Deploy Universal Charter

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "18"
    - name: Install markdown-transclusion
      run: npm install -g markdown-transclusion@1.0.1
    - name: Process charter
      run: |
        cd charter
        npx markdown-transclusion v1.md > ../index_temp.html 2>/dev/null
        # Remove any command output lines and create clean index.html
        tail -n +4 ../index_temp.html > ../index.html
        rm ../index_temp.html
        echo "Charter processed to index.html"
    - name: Verify index.html created
      run: |
        ls -la index.html
        echo "First 10 lines of index.html:"
        head -10 index.html
        echo "File size: $(wc -c < index.html) bytes"
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: "."

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
EOF < /dev/null